# Generated by Django 2.0 on 2020-02-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubanmovie',
            name='pub_name',
            field=models.CharField(default=2000, max_length=6),
            preserve_default=False,
        ),
    ]
