# Generated by Django 2.0 on 2020-02-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_doubanmovie_pub_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doubanmovie',
            old_name='pub_name',
            new_name='pub_time',
        ),
    ]
