# Generated by Django 2.1.1 on 2020-02-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200219_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('pub_time', models.CharField(max_length=6)),
                ('pic_url', models.CharField(max_length=100)),
                ('detail_url', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=30)),
                ('star', models.CharField(max_length=10)),
                ('evaluate_num', models.CharField(max_length=10)),
                ('detail_title', models.CharField(max_length=100)),
                ('introduce', models.CharField(max_length=1000)),
                ('detail', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
