# Generated by Django 2.0 on 2020-02-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='classify',
            field=models.CharField(default='movie', max_length=10),
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie_tv',
        ),
    ]
