# Generated by Django 2.0 on 2020-03-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200225_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubanmovie',
            name='type',
            field=models.CharField(default='豆瓣top250', max_length=30),
        ),
    ]
