# Generated by Django 2.0 on 2021-01-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20200327_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubanmovie',
            name='play_url',
            field=models.CharField(default='暂无', max_length=500, verbose_name='电影资源链接'),
        ),
        migrations.AddField(
            model_name='movie',
            name='play_url',
            field=models.CharField(default='暂无', max_length=500, verbose_name='电影资源链接'),
        ),
    ]
