# Generated by Django 2.0 on 2020-02-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default=' ', max_length=5),
            preserve_default=False,
        ),
    ]
