# Generated by Django 2.0 on 2020-03-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('video_id', models.CharField(max_length=10)),
                ('current_time', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
