# Generated by Django 2.0 on 2020-03-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='evaluate_star',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
