# Generated by Django 2.0 on 2020-03-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200327_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='tag',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
